# hosts.yml
---
# Inventario per l'esecuzione dei playbook

all:
  hosts:
    localhost:
      ansible_connection: local
      # Variabile di esempio per specificare l'utente non-root se necessario
      ansible_user: stefanor
      ansible_ssh_private_key_file: ~/.ssh/

    monster-int:
      ansible_host: 192.168.7.16  # Indirizzo IP o hostname effettivo
      ansible_user: stefanor      # L'utente SSH da usare per la connessione
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # (Opzionale) Specifica una chiave diversa
      ansible_become: yes          # Abilita il privilegio (sudo) per questo host
      ansible_python_interpreter: /usr/bin/python3 # (Opzionale) Specifica l'interprete Python

    monster-out:
      ansible_host: stefanor.ddns.net  # Indirizzo IP o hostname effettivo
      ansible_user: stefanor      # L'utente SSH da usare per la connessione
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519 # (Opzionale) Specifica una chiave diversa
      ansible_become: yes          # Abilita il privilegio (sudo) per questo host
      ansible_python_interpreter: /usr/bin/python3 # (Opzionale) Specifica l'interprete Python
