# hosts.yml
---
# Inventario per l'esecuzione dei playbook

all:
  hosts:
    localhost:
      ansible_connection: local
      # Variabile di esempio per specificare l'utente non-root se necessario
      # ansible_user: tuo_nome_utente
      